### ISSUE TITLE
[Spike] Tablet charting

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex-attic/CIAPI.Js#8]
This is a spike to evaluate what changes need to be made to jqPlot to enable candlestick charts (based on CityIndex price data) on a tablet device.

The spike should be optimised to function on:
- An Android tablet running Honeycomb 3.1 for a 10" screen size (e.g the Motorola Xoom)
- An iPad 2.0

==Functional requirements==

The spike should look something like the following:
<img src="https://docs.google.com/drawings/pub?id=1caLm7KQmLk5lBgqRXaAlewsRCvYwwi5KuwJGoHty-aY&w=962&h=720">
- Optimised for landscape mode; with the chart occupying 3/4 of the screen.  The right 1/4 will contain widgets displaying textual market information & a deal ticket.
- The chart is a candlestick plot using data pulled from the CIAPI.
- Your existing open position is shown as a bold line, along with some text showing the quantity and your current P&L.  The P&L needs to be updated dynamically (assume a javascript event that will be calling a function or the chart or manipulating a specific DOM element every few seconds)
- The stop & limit orders relating to your open position are plotted as dotted lines, along with textual details.
- The right hand widgets (Market info & Deal ticket) are being developed separately.  
- The chart should be scrollable left & right using a "swipe/flick" gesture
- The chart should be zoomable using a "pinch" gesture
- It should be possible to drag the lines up or down; and have this raise a javascript event passing data about the new position.  Eventually this would be used to link the lines to elements like the deal ticket input boxes.

==Implementation notes==
- https://github.com/cityindex/CIAPI.Js/tree/master/src/Chart contains the beginnings of a "CityIndex charting widget" based on jqplot. Note how data is retrieved from methods on CIAPI Js object; and how currently this CIAPI object just returns dummy data.  The spike should assume all API data comes from the CIAPI.Js object.  Just add any missing functions (and mock the data returned), as in the existing sample.  
- http://ciapiwordpress.ryanholder.com/ contains a working sample of the chart mentioned above.

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired to the [CityIndex Attic](https://github.com/orgs/cityindex-attic).
